language: python
python:
  - "2.7"

# command to install dependencies

install:
  - pip install .
  - pip install -r requirements.txt

# command to run tests
script: py.test

# DB setup
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing;" -U postgres
  - psql -c "CREATE USER aaron WITH PASSWORD '1';" -U postgres
